# Generated by Django 3.2 on 2021-05-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='descriptive_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentimentality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
