# Generated by Django 3.2 on 2021-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210529_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='descriptive_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentimentality_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
