# Generated by Django 3.2 on 2021-05-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manly',
        ),
    ]
