# Generated by Django 3.2 on 2021-05-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField(choices=[(0, 'Love'), (1, 'Smile'), (2, 'Neutral'), (4, 'Worried'), (5, 'Sad')], default=2)),
                ('time_felt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('social_media_link', models.CharField(blank=True, max_length=60)),
                ('face_pic', models.ImageField(blank=True, upload_to=user_dashboard.models.friend_pic_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='manly_points',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Friend_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.ManyToManyField(to='user_dashboard.Friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Emotion_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.ManyToManyField(to='user_dashboard.Emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
