# Generated by Django 3.2 on 2021-05-29 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20210529_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('manly_points', models.IntegerField(default=20)),
                ('users_done', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
