# Generated by Django 3.2 on 2021-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_auto_20210529_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_list',
            old_name='emotions',
            new_name='friends',
        ),
    ]
